name: Build Android

on:
  workflow_dispatch:
    inputs:
      version:
        description: "App version (optional)"
        required: false
        type: string
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_android:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.25.3

      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r28

      - name: Setup OpenJDK
        run: |
          sudo apt update && sudo apt install -y openjdk-17-jdk-headless
          /usr/lib/jvm/java-17-openjdk-amd64/bin/java --version

      - name: Build native library
        run: |
          make lib_install
          export PATH="$PATH:$(go env GOPATH)/bin"
          make lib_android
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Checkout correct branch
        if: github.ref == 'refs/heads/main-next'
        run: |
          cd clients/android
          git checkout main
      - name: Checkout dev branch
        if: github.ref == 'refs/heads/dev-next'
        run: |
          cd clients/android
          git checkout dev

      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle') }}

      - name: Update version (if provided)
        if: inputs.version != ''
        run: |
          go run -v ./cmd/internal/update_android_version --ci --version ${{ inputs.version }}

      - name: Build APKs
        run: |
          mkdir clients/android/app/libs
          cp libbox.aar clients/android/app/libs
          cd clients/android
          ./gradlew :app:assemblePlayRelease :app:assembleOtherRelease
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}

      - name: Prepare artifacts
        run: |
          mkdir -p dist
          cp clients/android/app/build/outputs/apk/play/release/*.apk dist || true
          cp clients/android/app/build/outputs/apk/other/release/*-universal.apk dist || true

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: dist
